//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabServerConnection
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estudiantes", Namespace="http://schemas.datacontract.org/2004/07/LabServerConnection")]
    public partial class Estudiantes : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EstApellidoField;
        
        private System.Nullable<int> EstMatriculaField;
        
        private string EstNombreField;
        
        private string EstPasswordField;
        
        private string EstReporteField;
        
        private string EstTotalNotaField;
        
        private string EstudianteIDField;
        
        private LabServerConnection.EstudiantesGrupos[] EstudiantesGruposField;
        
        private LabServerConnection.SimmulacionEstudiante[] SimmulacionEstudianteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstApellido
        {
            get
            {
                return this.EstApellidoField;
            }
            set
            {
                this.EstApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EstMatricula
        {
            get
            {
                return this.EstMatriculaField;
            }
            set
            {
                this.EstMatriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstNombre
        {
            get
            {
                return this.EstNombreField;
            }
            set
            {
                this.EstNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstPassword
        {
            get
            {
                return this.EstPasswordField;
            }
            set
            {
                this.EstPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstReporte
        {
            get
            {
                return this.EstReporteField;
            }
            set
            {
                this.EstReporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstTotalNota
        {
            get
            {
                return this.EstTotalNotaField;
            }
            set
            {
                this.EstTotalNotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstudianteID
        {
            get
            {
                return this.EstudianteIDField;
            }
            set
            {
                this.EstudianteIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.EstudiantesGrupos[] EstudiantesGrupos
        {
            get
            {
                return this.EstudiantesGruposField;
            }
            set
            {
                this.EstudiantesGruposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.SimmulacionEstudiante[] SimmulacionEstudiante
        {
            get
            {
                return this.SimmulacionEstudianteField;
            }
            set
            {
                this.SimmulacionEstudianteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstudiantesGrupos", Namespace="http://schemas.datacontract.org/2004/07/LabServerConnection")]
    public partial class EstudiantesGrupos : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EstGrupoIDField;
        
        private string EstudianteIDField;
        
        private LabServerConnection.Estudiantes EstudiantesField;
        
        private System.Nullable<int> GrupoIDField;
        
        private LabServerConnection.Grupos GruposField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstGrupoID
        {
            get
            {
                return this.EstGrupoIDField;
            }
            set
            {
                this.EstGrupoIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstudianteID
        {
            get
            {
                return this.EstudianteIDField;
            }
            set
            {
                this.EstudianteIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.Estudiantes Estudiantes
        {
            get
            {
                return this.EstudiantesField;
            }
            set
            {
                this.EstudiantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GrupoID
        {
            get
            {
                return this.GrupoIDField;
            }
            set
            {
                this.GrupoIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.Grupos Grupos
        {
            get
            {
                return this.GruposField;
            }
            set
            {
                this.GruposField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimmulacionEstudiante", Namespace="http://schemas.datacontract.org/2004/07/LabServerConnection")]
    public partial class SimmulacionEstudiante : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EstudianteIdField;
        
        private LabServerConnection.Estudiantes EstudiantesField;
        
        private string NotaField;
        
        private long SimEstIdField;
        
        private System.Nullable<int> SimulacionIdField;
        
        private LabServerConnection.Simulaciones SimulacionesField;
        
        private string descField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstudianteId
        {
            get
            {
                return this.EstudianteIdField;
            }
            set
            {
                this.EstudianteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.Estudiantes Estudiantes
        {
            get
            {
                return this.EstudiantesField;
            }
            set
            {
                this.EstudiantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nota
        {
            get
            {
                return this.NotaField;
            }
            set
            {
                this.NotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SimEstId
        {
            get
            {
                return this.SimEstIdField;
            }
            set
            {
                this.SimEstIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SimulacionId
        {
            get
            {
                return this.SimulacionIdField;
            }
            set
            {
                this.SimulacionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.Simulaciones Simulaciones
        {
            get
            {
                return this.SimulacionesField;
            }
            set
            {
                this.SimulacionesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grupos", Namespace="http://schemas.datacontract.org/2004/07/LabServerConnection")]
    public partial class Grupos : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LabServerConnection.EstudiantesGrupos[] EstudiantesGruposField;
        
        private int GrupoIDField;
        
        private string GrupoNombreField;
        
        private string GrupoProfesorField;
        
        private string NotaPromedioField;
        
        private LabServerConnection.Profesores ProfesoresField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.EstudiantesGrupos[] EstudiantesGrupos
        {
            get
            {
                return this.EstudiantesGruposField;
            }
            set
            {
                this.EstudiantesGruposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GrupoID
        {
            get
            {
                return this.GrupoIDField;
            }
            set
            {
                this.GrupoIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GrupoNombre
        {
            get
            {
                return this.GrupoNombreField;
            }
            set
            {
                this.GrupoNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GrupoProfesor
        {
            get
            {
                return this.GrupoProfesorField;
            }
            set
            {
                this.GrupoProfesorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotaPromedio
        {
            get
            {
                return this.NotaPromedioField;
            }
            set
            {
                this.NotaPromedioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.Profesores Profesores
        {
            get
            {
                return this.ProfesoresField;
            }
            set
            {
                this.ProfesoresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profesores", Namespace="http://schemas.datacontract.org/2004/07/LabServerConnection")]
    public partial class Profesores : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LabServerConnection.Grupos[] GruposField;
        
        private string ProfApellidoField;
        
        private string ProfNombreField;
        
        private string ProfPasswordField;
        
        private string ProfesorIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.Grupos[] Grupos
        {
            get
            {
                return this.GruposField;
            }
            set
            {
                this.GruposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfApellido
        {
            get
            {
                return this.ProfApellidoField;
            }
            set
            {
                this.ProfApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfNombre
        {
            get
            {
                return this.ProfNombreField;
            }
            set
            {
                this.ProfNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfPassword
        {
            get
            {
                return this.ProfPasswordField;
            }
            set
            {
                this.ProfPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfesorId
        {
            get
            {
                return this.ProfesorIdField;
            }
            set
            {
                this.ProfesorIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Simulaciones", Namespace="http://schemas.datacontract.org/2004/07/LabServerConnection")]
    public partial class Simulaciones : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> SimCantFallosField;
        
        private System.Nullable<long> SimDuracionField;
        
        private int SimIDField;
        
        private string SimNombreField;
        
        private LabServerConnection.SimmulacionEstudiante[] SimmulacionEstudianteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SimCantFallos
        {
            get
            {
                return this.SimCantFallosField;
            }
            set
            {
                this.SimCantFallosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> SimDuracion
        {
            get
            {
                return this.SimDuracionField;
            }
            set
            {
                this.SimDuracionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SimID
        {
            get
            {
                return this.SimIDField;
            }
            set
            {
                this.SimIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SimNombre
        {
            get
            {
                return this.SimNombreField;
            }
            set
            {
                this.SimNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.SimmulacionEstudiante[] SimmulacionEstudiante
        {
            get
            {
                return this.SimmulacionEstudianteField;
            }
            set
            {
                this.SimmulacionEstudianteField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServiceLab")]
public interface IServiceLab
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLab/RegistrarMatricula", ReplyAction="http://tempuri.org/IServiceLab/RegistrarMatriculaResponse")]
    bool RegistrarMatricula(string matricula, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLab/ObtenerEstudiantes", ReplyAction="http://tempuri.org/IServiceLab/ObtenerEstudiantesResponse")]
    LabServerConnection.Estudiantes[] ObtenerEstudiantes(string idEstudiantes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLab/ObtenerPass", ReplyAction="http://tempuri.org/IServiceLab/ObtenerPassResponse")]
    string ObtenerPass(string idEstudiantes);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLab/GenerarReporteEstudiante", ReplyAction="http://tempuri.org/IServiceLab/GenerarReporteEstudianteResponse")]
    string GenerarReporteEstudiante(string estudianteID);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLab/RegistrarEsudiante", ReplyAction="http://tempuri.org/IServiceLab/RegistrarEsudianteResponse")]
    bool RegistrarEsudiante(string id, string name, string lastname, int matricula);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLab/RegistrarProfesor", ReplyAction="http://tempuri.org/IServiceLab/RegistrarProfesorResponse")]
    bool RegistrarProfesor(string id, string name, string lastname);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLab/RegistrarCurso", ReplyAction="http://tempuri.org/IServiceLab/RegistrarCursoResponse")]
    bool RegistrarCurso(string name, string idprofesor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLab/RegistrarCursoestudiante", ReplyAction="http://tempuri.org/IServiceLab/RegistrarCursoestudianteResponse")]
    bool RegistrarCursoestudiante(int idCurso, string idEstudiante);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceLab/RegistrarSimulacion", ReplyAction="http://tempuri.org/IServiceLab/RegistrarSimulacionResponse")]
    bool RegistrarSimulacion(string name, int fallos, int duracion);
    
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceLabChannel : IServiceLab, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceLabClient : System.ServiceModel.ClientBase<IServiceLab>, IServiceLab
{
    
    public ServiceLabClient()
    {
    }
    
    public ServiceLabClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceLabClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceLabClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceLabClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool RegistrarMatricula(string matricula, string password)
    {
        return base.Channel.RegistrarMatricula(matricula, password);
    }
    
    public LabServerConnection.Estudiantes[] ObtenerEstudiantes(string idEstudiantes)
    {
        return base.Channel.ObtenerEstudiantes(idEstudiantes);
    }
    
    public string ObtenerPass(string idEstudiantes)
    {
        return base.Channel.ObtenerPass(idEstudiantes);
    }
    
    public string GenerarReporteEstudiante(string estudianteID)
    {
        return base.Channel.GenerarReporteEstudiante(estudianteID);
    }
    
    public bool RegistrarEsudiante(string id, string name, string lastname, int matricula)
    {
        return base.Channel.RegistrarEsudiante(id, name, lastname, matricula);
    }
    
    public bool RegistrarProfesor(string id, string name, string lastname)
    {
        return base.Channel.RegistrarProfesor(id, name, lastname);
    }
    
    
    public bool RegistrarCurso(string name, string idprofesor)
    {
        return base.Channel.RegistrarCurso(name, idprofesor);
    }
    
    public bool RegistrarCursoestudiante(int idCurso, string idEstudiante)
    {
        return base.Channel.RegistrarCursoestudiante(idCurso, idEstudiante);
    }
    
    public bool RegistrarSimulacion(string name, int fallos, int duracion)
    {
        return base.Channel.RegistrarSimulacion(name, fallos, duracion);
    }
    
}
