//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabServerConnection
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estudiantes", Namespace="http://schemas.datacontract.org/2004/07/LabServerConnection")]
    public partial class Estudiantes : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EstApellidoField;
        
        private System.Nullable<int> EstIDMoodleField;
        
        private string EstMatriculaField;
        
        private string EstNombreField;
        
        private string EstReporteField;
        
        private string EstTotalNotaField;
        
        private string EstudianteIDField;
        
        private LabServerConnection.EstudiantesGrupos[] EstudiantesGruposField;
        
        private LabServerConnection.SimmulacionEstudiante[] SimmulacionEstudianteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstApellido
        {
            get
            {
                return this.EstApellidoField;
            }
            set
            {
                this.EstApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EstIDMoodle
        {
            get
            {
                return this.EstIDMoodleField;
            }
            set
            {
                this.EstIDMoodleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstMatricula
        {
            get
            {
                return this.EstMatriculaField;
            }
            set
            {
                this.EstMatriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstNombre
        {
            get
            {
                return this.EstNombreField;
            }
            set
            {
                this.EstNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstReporte
        {
            get
            {
                return this.EstReporteField;
            }
            set
            {
                this.EstReporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstTotalNota
        {
            get
            {
                return this.EstTotalNotaField;
            }
            set
            {
                this.EstTotalNotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstudianteID
        {
            get
            {
                return this.EstudianteIDField;
            }
            set
            {
                this.EstudianteIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.EstudiantesGrupos[] EstudiantesGrupos
        {
            get
            {
                return this.EstudiantesGruposField;
            }
            set
            {
                this.EstudiantesGruposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.SimmulacionEstudiante[] SimmulacionEstudiante
        {
            get
            {
                return this.SimmulacionEstudianteField;
            }
            set
            {
                this.SimmulacionEstudianteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EstudiantesGrupos", Namespace="http://schemas.datacontract.org/2004/07/LabServerConnection")]
    public partial class EstudiantesGrupos : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EstGrupoIDField;
        
        private string EstudianteIDField;
        
        private LabServerConnection.Estudiantes EstudiantesField;
        
        private System.Nullable<int> GrupoIDField;
        
        private LabServerConnection.Grupos GruposField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstGrupoID
        {
            get
            {
                return this.EstGrupoIDField;
            }
            set
            {
                this.EstGrupoIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstudianteID
        {
            get
            {
                return this.EstudianteIDField;
            }
            set
            {
                this.EstudianteIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.Estudiantes Estudiantes
        {
            get
            {
                return this.EstudiantesField;
            }
            set
            {
                this.EstudiantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GrupoID
        {
            get
            {
                return this.GrupoIDField;
            }
            set
            {
                this.GrupoIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.Grupos Grupos
        {
            get
            {
                return this.GruposField;
            }
            set
            {
                this.GruposField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SimmulacionEstudiante", Namespace="http://schemas.datacontract.org/2004/07/LabServerConnection")]
    public partial class SimmulacionEstudiante : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EstudianteIdField;
        
        private LabServerConnection.Estudiantes EstudiantesField;
        
        private string NotaField;
        
        private long SimEstIdField;
        
        private System.Nullable<int> SimulacionIdField;
        
        private LabServerConnection.Simulaciones SimulacionesField;
        
        private string descField;
        
        private System.Nullable<System.DateTime> fechaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstudianteId
        {
            get
            {
                return this.EstudianteIdField;
            }
            set
            {
                this.EstudianteIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.Estudiantes Estudiantes
        {
            get
            {
                return this.EstudiantesField;
            }
            set
            {
                this.EstudiantesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nota
        {
            get
            {
                return this.NotaField;
            }
            set
            {
                this.NotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SimEstId
        {
            get
            {
                return this.SimEstIdField;
            }
            set
            {
                this.SimEstIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SimulacionId
        {
            get
            {
                return this.SimulacionIdField;
            }
            set
            {
                this.SimulacionIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.Simulaciones Simulaciones
        {
            get
            {
                return this.SimulacionesField;
            }
            set
            {
                this.SimulacionesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desc
        {
            get
            {
                return this.descField;
            }
            set
            {
                this.descField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Grupos", Namespace="http://schemas.datacontract.org/2004/07/LabServerConnection")]
    public partial class Grupos : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LabServerConnection.EstudiantesGrupos[] EstudiantesGruposField;
        
        private int GrupoIDField;
        
        private string GrupoNombreField;
        
        private string GrupoProfesorField;
        
        private string NotaPromedioField;
        
        private LabServerConnection.Profesores ProfesoresField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.EstudiantesGrupos[] EstudiantesGrupos
        {
            get
            {
                return this.EstudiantesGruposField;
            }
            set
            {
                this.EstudiantesGruposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GrupoID
        {
            get
            {
                return this.GrupoIDField;
            }
            set
            {
                this.GrupoIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GrupoNombre
        {
            get
            {
                return this.GrupoNombreField;
            }
            set
            {
                this.GrupoNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GrupoProfesor
        {
            get
            {
                return this.GrupoProfesorField;
            }
            set
            {
                this.GrupoProfesorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotaPromedio
        {
            get
            {
                return this.NotaPromedioField;
            }
            set
            {
                this.NotaPromedioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.Profesores Profesores
        {
            get
            {
                return this.ProfesoresField;
            }
            set
            {
                this.ProfesoresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profesores", Namespace="http://schemas.datacontract.org/2004/07/LabServerConnection")]
    public partial class Profesores : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LabServerConnection.Grupos[] GruposField;
        
        private string ProfApellidoField;
        
        private System.Nullable<int> ProfIDMoodleField;
        
        private string ProfNombreField;
        
        private string ProfesorIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.Grupos[] Grupos
        {
            get
            {
                return this.GruposField;
            }
            set
            {
                this.GruposField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfApellido
        {
            get
            {
                return this.ProfApellidoField;
            }
            set
            {
                this.ProfApellidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProfIDMoodle
        {
            get
            {
                return this.ProfIDMoodleField;
            }
            set
            {
                this.ProfIDMoodleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfNombre
        {
            get
            {
                return this.ProfNombreField;
            }
            set
            {
                this.ProfNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProfesorId
        {
            get
            {
                return this.ProfesorIdField;
            }
            set
            {
                this.ProfesorIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Simulaciones", Namespace="http://schemas.datacontract.org/2004/07/LabServerConnection")]
    public partial class Simulaciones : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private LabServerConnection.Datosdinamicos[] DatosdinamicosField;
        
        private System.Nullable<int> SimCantFallosField;
        
        private System.Nullable<long> SimDuracionField;
        
        private int SimIDField;
        
        private string SimNombreField;
        
        private LabServerConnection.SimmulacionEstudiante[] SimmulacionEstudianteField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.Datosdinamicos[] Datosdinamicos
        {
            get
            {
                return this.DatosdinamicosField;
            }
            set
            {
                this.DatosdinamicosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SimCantFallos
        {
            get
            {
                return this.SimCantFallosField;
            }
            set
            {
                this.SimCantFallosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> SimDuracion
        {
            get
            {
                return this.SimDuracionField;
            }
            set
            {
                this.SimDuracionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SimID
        {
            get
            {
                return this.SimIDField;
            }
            set
            {
                this.SimIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SimNombre
        {
            get
            {
                return this.SimNombreField;
            }
            set
            {
                this.SimNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.SimmulacionEstudiante[] SimmulacionEstudiante
        {
            get
            {
                return this.SimmulacionEstudianteField;
            }
            set
            {
                this.SimmulacionEstudianteField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Datosdinamicos", Namespace="http://schemas.datacontract.org/2004/07/LabServerConnection")]
    public partial class Datosdinamicos : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<long> DataIntField;
        
        private string DatastringField;
        
        private string NombreIDField;
        
        private LabServerConnection.Simulaciones SimulacionesField;
        
        private System.Nullable<int> simulacionIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DataInt
        {
            get
            {
                return this.DataIntField;
            }
            set
            {
                this.DataIntField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Datastring
        {
            get
            {
                return this.DatastringField;
            }
            set
            {
                this.DatastringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreID
        {
            get
            {
                return this.NombreIDField;
            }
            set
            {
                this.NombreIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LabServerConnection.Simulaciones Simulaciones
        {
            get
            {
                return this.SimulacionesField;
            }
            set
            {
                this.SimulacionesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> simulacionID
        {
            get
            {
                return this.simulacionIDField;
            }
            set
            {
                this.simulacionIDField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IServiceLab")]
public interface IServiceLab
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/RegistrarMatricula", ReplyAction = "http://tempuri.org/IServiceLab/RegistrarMatriculaResponse")]
    bool RegistrarMatricula(string matricula, string password);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/ObtenerEstudiantes", ReplyAction = "http://tempuri.org/IServiceLab/ObtenerEstudiantesResponse")]
    LabServerConnection.Estudiantes[] ObtenerEstudiantes(string idEstudiantes);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/ObtenerPassID", ReplyAction = "http://tempuri.org/IServiceLab/ObtenerPassIDResponse")]
    int ObtenerPassID(string idEstudiantes);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/ObtenerPassIDProf", ReplyAction = "http://tempuri.org/IServiceLab/ObtenerPassIDProfResponse")]
    int ObtenerPassIDProf(string idprof);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/ObtenerGroupName", ReplyAction = "http://tempuri.org/IServiceLab/ObtenerGroupNameResponse")]
    string ObtenerGroupName(int idGroup);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/GenerarReporteEstudiante", ReplyAction = "http://tempuri.org/IServiceLab/GenerarReporteEstudianteResponse")]
    string GenerarReporteEstudiante(string estudianteID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/RegistrarEsudiante", ReplyAction = "http://tempuri.org/IServiceLab/RegistrarEsudianteResponse")]
    bool RegistrarEsudiante(string id, string name, string lastname, string matricula, int idMoodle);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/RegistrarProfesor", ReplyAction = "http://tempuri.org/IServiceLab/RegistrarProfesorResponse")]
    bool RegistrarProfesor(string id, string name, string lastname, int idMoodle);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/RegistrarCurso", ReplyAction = "http://tempuri.org/IServiceLab/RegistrarCursoResponse")]
    bool RegistrarCurso(string name, int id, string idprofesor);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/ActualizarCurso", ReplyAction = "http://tempuri.org/IServiceLab/ActualizarCursoResponse")]
    bool ActualizarCurso(string name, int id, string idprofesor);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/CambiosCursoEstudiante", ReplyAction = "http://tempuri.org/IServiceLab/CambiosCursoEstudianteResponse")]
    bool CambiosCursoEstudiante(string name, int id);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/RegistrarCursoestudiante", ReplyAction = "http://tempuri.org/IServiceLab/RegistrarCursoestudianteResponse")]
    bool RegistrarCursoestudiante(int idCurso, string idEstudiante);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/RegistrarSimulacion", ReplyAction = "http://tempuri.org/IServiceLab/RegistrarSimulacionResponse")]
    bool RegistrarSimulacion(string name, int fallos, int duracion);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/RegistrarSimulacionEst", ReplyAction = "http://tempuri.org/IServiceLab/RegistrarSimulacionEstResponse")]
    bool RegistrarSimulacionEst(string NombreSim, string idEstudiante, string nota);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/verificarEstudiante", ReplyAction = "http://tempuri.org/IServiceLab/verificarEstudianteResponse")]
    bool verificarEstudiante(string idEstudiantes, string password);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/verificarProfesor", ReplyAction = "http://tempuri.org/IServiceLab/verificarProfesorResponse")]
    bool verificarProfesor(string idprofesor, string password);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/GuardarCambioDinamicos", ReplyAction = "http://tempuri.org/IServiceLab/GuardarCambioDinamicosResponse")]
    bool GuardarCambioDinamicos(string simulacion, string[] dato, int dato2, string nivel, string[] nombreData);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/BuscarDatosD", ReplyAction = "http://tempuri.org/IServiceLab/BuscarDatosDResponse")]
    string[] BuscarDatosD(string simulacion, string nivel, string[] nombreData);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/devolverNotasEst", ReplyAction = "http://tempuri.org/IServiceLab/devolverNotasEstResponse")]
    string[] devolverNotasEst(string idEstudiantes);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/devolverNotasEstPorFecha", ReplyAction = "http://tempuri.org/IServiceLab/devolverNotasEstPorFechaResponse")]
    string[] devolverNotasEstPorFecha(string idEstudiantes, System.DateTime date);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/updateNota", ReplyAction = "http://tempuri.org/IServiceLab/updateNotaResponse")]
    bool updateNota(string NombreSim, string idEstudiante, string nota, int id);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/datosUser", ReplyAction = "http://tempuri.org/IServiceLab/datosUserResponse")]
    void datosUser(string idEstudiante);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/datosUserProf", ReplyAction = "http://tempuri.org/IServiceLab/datosUserProfResponse")]
    void datosUserProf(string idProf);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/DarLinkDocumentos", ReplyAction = "http://tempuri.org/IServiceLab/DarLinkDocumentosResponse")]
    string[] DarLinkDocumentos(string data);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/ActualizarSimulacion", ReplyAction = "http://tempuri.org/IServiceLab/ActualizarSimulacionResponse")]
    bool ActualizarSimulacion(string name, int fallos, int duracion);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/DatosSimulacion", ReplyAction = "http://tempuri.org/IServiceLab/DatosSimulacionResponse")]
    long[] DatosSimulacion(string name);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/DarListagruposProfesor", ReplyAction = "http://tempuri.org/IServiceLab/DarListagruposProfesorResponse")]
    string[] DarListagruposProfesor(string idProfesor);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/DarListaEstudentGrupo", ReplyAction = "http://tempuri.org/IServiceLab/DarListaEstudentGrupoResponse")]
    string[] DarListaEstudentGrupo(string EstID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/DarListaEstudentGrupoInt", ReplyAction = "http://tempuri.org/IServiceLab/DarListaEstudentGrupoIntResponse")]
    int[] DarListaEstudentGrupoInt(string EstID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/GenerarReporteProfesor", ReplyAction = "http://tempuri.org/IServiceLab/GenerarReporteProfesorResponse")]
    string GenerarReporteProfesor(int grupoId, string profesorID, System.DateTime date);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/DarListaEstudiantesGrupo", ReplyAction = "http://tempuri.org/IServiceLab/DarListaEstudiantesGrupoResponse")]
    LabServerConnection.Estudiantes[] DarListaEstudiantesGrupo(int grupoID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/RegistrarProfesorGrupo", ReplyAction = "http://tempuri.org/IServiceLab/RegistrarProfesorGrupoResponse")]
    bool RegistrarProfesorGrupo(string ProfID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/RegistrarEstudentGrupo", ReplyAction = "http://tempuri.org/IServiceLab/RegistrarEstudentGrupoResponse")]
    bool RegistrarEstudentGrupo(string EstID);


    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IServiceLab/aleluya", ReplyAction = "http://tempuri.org/IServiceLab/aleluyaResponse")]
    bool aleluya(string name);

}
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServiceLabChannel : IServiceLab, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServiceLabClient : System.ServiceModel.ClientBase<IServiceLab>, IServiceLab
{
    
    public ServiceLabClient()
    {
    }
    
    public ServiceLabClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServiceLabClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceLabClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServiceLabClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool RegistrarMatricula(string matricula, string password)
    {
        return base.Channel.RegistrarMatricula(matricula, password);
    }
    
    public LabServerConnection.Estudiantes[] ObtenerEstudiantes(string idEstudiantes)
    {
        return base.Channel.ObtenerEstudiantes(idEstudiantes);
    }
    
    public int ObtenerPassID(string idEstudiantes)
    {
        return base.Channel.ObtenerPassID(idEstudiantes);
    }
    
    public int ObtenerPassIDProf(string idprof)
    {
        return base.Channel.ObtenerPassIDProf(idprof);
    }
    
    public string ObtenerGroupName(int idGroup)
    {
        return base.Channel.ObtenerGroupName(idGroup);
    }
    
    public string GenerarReporteEstudiante(string estudianteID)
    {
        return base.Channel.GenerarReporteEstudiante(estudianteID);
    }
    
    public bool RegistrarEsudiante(string id, string name, string lastname, string matricula, int idMoodle)
    {
        return base.Channel.RegistrarEsudiante(id, name, lastname, matricula, idMoodle);
    }
    
    public bool RegistrarProfesor(string id, string name, string lastname, int idMoodle)
    {
        return base.Channel.RegistrarProfesor(id, name, lastname, idMoodle);
    }
    
    public bool RegistrarCurso(string name, int id, string idprofesor)
    {
        return base.Channel.RegistrarCurso(name, id, idprofesor);
    }
    
    public bool ActualizarCurso(string name, int id, string idprofesor)
    {
        return base.Channel.ActualizarCurso(name, id, idprofesor);
    }
    
    public bool CambiosCursoEstudiante(string name, int id)
    {
        return base.Channel.CambiosCursoEstudiante(name, id);
    }
    
    public bool RegistrarCursoestudiante(int idCurso, string idEstudiante)
    {
        return base.Channel.RegistrarCursoestudiante(idCurso, idEstudiante);
    }
    
    public bool RegistrarSimulacion(string name, int fallos, int duracion)
    {
        return base.Channel.RegistrarSimulacion(name, fallos, duracion);
    }
    
    public bool RegistrarSimulacionEst(string NombreSim, string idEstudiante, string nota)
    {
        return base.Channel.RegistrarSimulacionEst(NombreSim, idEstudiante, nota);
    }
    
    public bool verificarEstudiante(string idEstudiantes, string password)
    {
        return base.Channel.verificarEstudiante(idEstudiantes, password);
    }
    
    public bool verificarProfesor(string idprofesor, string password)
    {
        return base.Channel.verificarProfesor(idprofesor, password);
    }
    
    public bool GuardarCambioDinamicos(string simulacion, string[] dato, int dato2, string nivel, string[] nombreData)
    {
        return base.Channel.GuardarCambioDinamicos(simulacion, dato, dato2, nivel, nombreData);
    }
    
    public string[] BuscarDatosD(string simulacion, string nivel, string[] nombreData)
    {
        return base.Channel.BuscarDatosD(simulacion, nivel, nombreData);
    }
    
    public string[] devolverNotasEst(string idEstudiantes)
    {
        return base.Channel.devolverNotasEst(idEstudiantes);
    }
    
    public string[] devolverNotasEstPorFecha(string idEstudiantes, System.DateTime date)
    {
        return base.Channel.devolverNotasEstPorFecha(idEstudiantes, date);
    }
    
    public bool updateNota(string NombreSim, string idEstudiante, string nota, int id)
    {
        return base.Channel.updateNota(NombreSim, idEstudiante, nota, id);
    }
    
    public void datosUser(string idEstudiante)
    {
        base.Channel.datosUser(idEstudiante);
    }
    
    public void datosUserProf(string idProf)
    {
        base.Channel.datosUserProf(idProf);
    }
    
    public string[] DarLinkDocumentos(string data)
    {
        return base.Channel.DarLinkDocumentos(data);
    }
    
    public bool ActualizarSimulacion(string name, int fallos, int duracion)
    {
        return base.Channel.ActualizarSimulacion(name, fallos, duracion);
    }
    
    public long[] DatosSimulacion(string name)
    {
        return base.Channel.DatosSimulacion(name);
    }
    
    public string[] DarListagruposProfesor(string idProfesor)
    {
        return base.Channel.DarListagruposProfesor(idProfesor);
    }
    
    public string[] DarListaEstudentGrupo(string EstID)
    {
        return base.Channel.DarListaEstudentGrupo(EstID);
    }
    
    public int[] DarListaEstudentGrupoInt(string EstID)
    {
        return base.Channel.DarListaEstudentGrupoInt(EstID);
    }
    
    public string GenerarReporteProfesor(int grupoId, string profesorID, System.DateTime date)
    {
        return base.Channel.GenerarReporteProfesor(grupoId, profesorID, date);
    }
    
    public LabServerConnection.Estudiantes[] DarListaEstudiantesGrupo(int grupoID)
    {
        return base.Channel.DarListaEstudiantesGrupo(grupoID);
    }
    
    public bool RegistrarProfesorGrupo(string ProfID)
    {
        return base.Channel.RegistrarProfesorGrupo(ProfID);
    }
    
    public bool RegistrarEstudentGrupo(string EstID)
    {
        return base.Channel.RegistrarEstudentGrupo(EstID);
    }
    
    public bool aleluya(string name)
    {
        return base.Channel.aleluya(name);
    }
    
}
